server:
  port: 8012

spring:
  application:
    name: UMS-API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: UMS-LOGIN
          uri: lb://UMS-USERS-SERVICE
          predicates:
            - Path=/users/login
            - Method=POST
          
        - id: UMS-EMPLOYEE-SERVICE
          uri: lb://UMS-EMPLOYEE-SERVICE
          predicates:
            - Path=/employees/**,/designations/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: CircuitBreaker
              args:
                name: UMS-EMPLOYEE-SERVICE
                fallbackuri: forward:/employeeServiceFallBack
            - name: AuthorizationHeaderFilter 
                
        - id: UMS-DEPARTMENT-SERVICE
          uri: lb://UMS-DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: CircuitBreaker
              args:
                name: UMS-DEPARTMENT-SERVICE
                fallbackuri: forward:/departmentServiceFallBack
            - name: AuthorizationHeaderFilter 
        
        - id: UMS-ADMIN-SERVICE-USER
          uri: lb://UMS-USERS-SERVICE
          predicates:
            - Path=/users/**, /user/**
            - Method=GET,POST,PUT,DELETE,PATCH
          #filters:
            #- name: AuthorizationHeaderFilter
            
        - id: UMS-ADMIN-SERVICE-ROLES-ORG
          uri: lb://UMS-USERS-SERVICE
          predicates:
            - Path=/roles/**,/org/**,/permission/**
            - Method=GET,POST,PUT,DELETE,PATCH
          filters:
            - name: AuthorizationHeaderFilter
                     
        - id: UMS-BATCH-SERVICE
          uri: lb://UMS-BATCH-SERVICE
          predicates:
            - Path=/teams/**
            - Method=GET,POST
            
        - id: UMS-MEETINGS
          uri: lb://UMS-MEETING-SERVICE
          predicates:
            - Path=/meetings/**,/actions/**,/task/**,/taskCategory/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: AuthorizationHeaderFilter
        
        - id: NLP
          uri: lb://UMS-NLP-SERVICE
          predicates:
            - Path=/nlp/**
            - Method=GET,POST,PUT,DELETE
            
        - id: Notification
          uri: lb://UMS-NOTIFICATION-SERVICE
          predicates:
            - Path=/notification/**
            - Method=GET,POST,PUT,DELETE
            
        - id: BiReports
          uri: lb://UMS-BI-REPORTING-SERVICE
          predicates:
            - Path=/reports/**
            - Method=GET,POST,PUT,DELETE
token:
  expiration_time: 8640000
  secret: hgsd75767sdj87sd708bjh65
         
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
                    
#The below is added in git repository as part of UMS MS Config Server and not required here      
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
