server:
  port: 8012

spring:
  application:
    name: UMS-API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: UMS-LOGIN
          uri: lb://UMS-USERS-SERVICE
          predicates:
            - Path=/users/login
            - Method=POST
          
        - id: UMS-EMPLOYEE-SERVICE
          uri: lb://UMS-EMPLOYEE-SERVICE
          predicates:
            - Path=/employees/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: CircuitBreaker
              args:
                name: UMS-EMPLOYEE-SERVICE
                fallbackuri: forward:/employeeServiceFallBack
                
        - id: UMS-DEPARTMENT-SERVICE
          uri: lb://UMS-DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: UMS-DEPARTMENT-SERVICE
                fallbackuri: forward:/departmentServiceFallBack
        
        - id: UMS-AUTHENTICATION-SERVICE
          uri: lb://UMS-USERS-SERVICE
          predicates:
            - Path=/users/**
            - Method=GET,POST,PUT,DELETE,PATCH
                     
        - id: GET-USER-EVENTS
          uri: lb://UMS-BATCH-SERVICE
          predicates:
            - Path=/teams/**
            - Method=GET,POST
            
        - id: AZURE-USERS
          uri: lb://UMS-MEETING-SERVICE
          predicates:
            - Path=/api/actions/**
            - Method=GET,POST,PUT,DELETE
            
        - id: EVENTS
          uri: lb://UMS-MEETING-SERVICE
          predicates:
            - Path=/meetings/**
            - Method=GET,POST,PUT,DELETE
            
        - id: TASKS
          uri: lb://UMS-MEETING-SERVICE
          predicates:
            - Path=/task/**
            - Method=GET,POST,PUT,DELETE
        
        - id: NLP
          uri: lb://UMS-NLP-SERVICE
          predicates:
            - Path=/nlp/**
            - Method=GET,POST,PUT,DELETE
            
        
    
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
                    
#The below is added in git repository as part of UMS MS Config Server and not required here      
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
